# -*- coding: utf-8 -*-
"""Copy of AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DnAvY3jD_igGdx7_OimBJIG-hQP6Eu99
"""

!nvidia-smi

!pip install diffusers==0.11.1
!pip install transformers scipy ftfy accelerate

import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)

pipe = pipe.to("cuda")

#free discreption

prompt = "coloful paintings"
X="Mosque  mountains"
promptX = X + prompt
image = pipe(promptX).images[0]  
image

#japan
prompt = " tokyo Japanese Kimono tea Ikebana anime word hiragana Senso-ji Temple"
X="inpanting colorfull "
promptX = X + prompt
image = pipe(promptX).images[0]  

image

#paris
prompt = "inpanting  paris    Notre-Dame cathedral colorfull art Eiffel tower"
X=" "
promptX = X + prompt
image = pipe(prompt).images[0]  

image

#saudi
prompt = "inpanting realstic saudi  neom caligraphy islamic alula  date colorfull clocktower aramco"
X=" "
promptX = X + prompt
image = pipe(prompt).images[0]  

image

!pip install flask_ngrok